import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#f7f6f2] text-[#171717]"><div className="mx-auto max-w-4xl px-5 sm:px-8">
      <header className="flex items-center justify-between border-b border-neutral-300/80 py-6"><Link href="/" className="font-serif text-[22px] font-semibold">POSTCRAFT</Link><Link href="/contact" className="text-xs text-neutral-500">Contact</Link></header>
      <article className="py-14 sm:py-20"><div className="text-[11px] uppercase tracking-[.2em] text-neutral-500">Legal</div><h1 className="mt-4 font-serif text-5xl tracking-[-.04em] sm:text-6xl">Privacy Policy</h1><p className="mt-4 text-sm text-neutral-500">Last updated: September 23, 2026</p>
        <div className="prose prose-neutral mt-10 max-w-none text-sm leading-7"><h2>1. Information we collect</h2><p>Ninety6 AI Solutions may collect account information such as your name and email address, content you create in PostCraft, connected service information, billing and subscription information, and technical information needed to operate and secure the service.</p><h2>2. How we use information</h2><p>We use information to provide PostCraft, authenticate accounts, generate requested content, process subscriptions and payments, provide support, prevent misuse, maintain security, and improve the reliability of the service.</p><h2>3. Payments</h2><p>Payments are processed through Razorpay. PostCraft does not request or store your full card number, CVV or other sensitive payment credentials on its own servers.</p><h2>4. Connected services</h2><p>If you connect LinkedIn or another supported service, information required for that connection and requested publishing actions may be processed to provide the feature. You can disconnect supported accounts from the product where available.</p><h2>5. Data sharing</h2><p>We may use service providers such as hosting, authentication, database, AI infrastructure and payment providers to operate PostCraft. We do not sell personal information.</p><h2>6. Security</h2><p>We use reasonable technical and organizational measures to protect information. No internet service can guarantee absolute security.</p><h2>7. Your choices</h2><p>You may contact us regarding access, correction or deletion of information associated with your account, subject to applicable legal and operational requirements.</p><h2>8. Contact</h2><p>Ninety6 AI Solutions<br/>615 Symphony Park Homes, Beeramguda, Hyderabad, Telangana, India.<br/>Email: <a href="mailto:mpari@outlook.com">mpari@outlook.com</a></p></div>
      </article>
      <footer className="border-t border-neutral-300/80 py-8 text-xs text-neutral-500"><Link href="/terms">Terms</Link> · <Link href="/refunds">Refunds & Cancellation</Link> · <Link href="/contact">Contact</Link></footer>
    </div></main>
  );
}
