import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#f7f6f2] text-[#171717]"><div className="mx-auto max-w-4xl px-5 sm:px-8">
      <header className="flex items-center justify-between border-b border-neutral-300/80 py-6"><Link href="/" className="font-serif text-[22px] font-semibold">POSTCRAFT</Link><Link href="/contact" className="text-xs text-neutral-500">Contact</Link></header>
      <article className="py-14 sm:py-20"><div className="text-[11px] uppercase tracking-[.2em] text-neutral-500">Legal</div><h1 className="mt-4 font-serif text-5xl tracking-[-.04em] sm:text-6xl">Terms of Service</h1><p className="mt-4 text-sm text-neutral-500">Last updated: September 23, 2026</p>
        <div className="prose prose-neutral mt-10 max-w-none text-sm leading-7"><h2>1. Service</h2><p>PostCraft is an AI-assisted content and publishing service operated by Ninety6 AI Solutions. You may use the service only in accordance with these terms and applicable law.</p><h2>2. Account</h2><p>You are responsible for maintaining the security of your account and for activity performed through it. Account information should be accurate and current.</p><h2>3. AI-generated content</h2><p>PostCraft assists with research, drafting and editing. AI output may contain errors. You are responsible for reviewing content, sources, claims and publishing decisions before publication.</p><h2>4. User content</h2><p>You retain responsibility for content you submit or publish through PostCraft and must have the rights and permissions necessary to use it.</p><h2>5. Trial and subscription</h2><p>Eligible new users may receive a 15-day free trial. After the trial, a 3-day grace period may apply. Continued paid use is available through the displayed PostCraft Pro subscription at ₹499 per month.</p><h2>6. Payments</h2><p>Paid subscriptions are processed through Razorpay. Subscription status may be updated based on successful payment and verified payment notifications.</p><h2>7. Acceptable use</h2><p>You must not use PostCraft for unlawful activity, fraud, impersonation, harassment, unauthorized access, or content that infringes another person's rights.</p><h2>8. Changes and availability</h2><p>We may update the service and these terms from time to time. We may also suspend access where reasonably necessary for security, maintenance or misuse.</p><h2>9. Contact</h2><p>Ninety6 AI Solutions<br/>615 Symphony Park Homes, Beeramguda, Hyderabad, Telangana, India.<br/>Email: <a href="mailto:mpari@outlook.com">mpari@outlook.com</a></p></div>
      </article>
      <footer className="border-t border-neutral-300/80 py-8 text-xs text-neutral-500"><Link href="/privacy">Privacy</Link> · <Link href="/refunds">Refunds & Cancellation</Link> · <Link href="/contact">Contact</Link></footer>
    </div></main>
  );
}
