import { getAIProvider } from "@/lib/ai/provider";
import { parseJsonObject } from "@/lib/ai/json";

export type PostcardCandidate = {
  headline: string;
  body: string;
  closing: string;
  linkedinPost: string;
};

export type QualityResult = {
  pass: boolean;
  score: number;
  reasons: string[];
};

function normalize(value: string) {
  return value
    .toLowerCase()
    .normalize("NFKC")
    .replace(/[’‘]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[^a-z0-9\s']/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tokens(value: string) {
  return normalize(value).split(" ").filter((token) => token.length > 1);
}

function jaccard(a: string, b: string) {
  const left = new Set(tokens(a));
  const right = new Set(tokens(b));
  if (!left.size || !right.size) return 0;
  let shared = 0;
  for (const token of left) if (right.has(token)) shared += 1;
  return shared / new Set([...left, ...right]).size;
}

function repeatedSentence(value: string) {
  const sentences = value
    .split(/[.!?]+/)
    .map((part) => normalize(part))
    .filter((part) => part.length >= 20);
  const seen = new Set<string>();
  for (const sentence of sentences) {
    if (seen.has(sentence)) return true;
    seen.add(sentence);
  }
  for (let i = 0; i < sentences.length; i += 1) {
    for (let j = i + 1; j < sentences.length; j += 1) {
      if (jaccard(sentences[i], sentences[j]) >= 0.82) return true;
    }
  }
  return false;
}

function hasSuspiciousCharacters(value: string) {
  if (value.includes("\uFFFD")) return true;
  return /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F\uE000-\uF8FF]/u.test(value);
}

function hasExcessivePunctuation(value: string) {
  return /([!?.,:;])\1{3,}/.test(value) || /\s{3,}/.test(value);
}

function containsMetaLanguage(value: string) {
  return /\b(as an ai|here(?:'s| is) (?:a|the) (?:linkedin )?(?:post|story)|let me know if you|i hope this helps|certainly!|sure!|generated by ai)\b/i.test(value);
}

export function evaluatePostcardDeterministic(candidate: PostcardCandidate): QualityResult {
  const reasons: string[] = [];
  const all = `${candidate.headline}\n${candidate.body}\n${candidate.closing}`;
  const headlineWords = tokens(candidate.headline).length;
  const bodyWords = tokens(candidate.body).length;
  const closingWords = tokens(candidate.closing).length;

  if (!candidate.headline || headlineWords < 3 || headlineWords > 12) reasons.push("headline_length");
  if (!candidate.body || bodyWords < 35 || bodyWords > 110) reasons.push("card_body_length");
  if (!candidate.closing || closingWords < 5 || closingWords > 24) reasons.push("closing_length");
  if (!candidate.linkedinPost || tokens(candidate.linkedinPost).length < 45) reasons.push("linkedin_too_short");
  if (hasSuspiciousCharacters(all) || hasSuspiciousCharacters(candidate.linkedinPost)) reasons.push("suspicious_characters");
  if (hasExcessivePunctuation(all) || hasExcessivePunctuation(candidate.linkedinPost)) reasons.push("excessive_punctuation");
  if (repeatedSentence(all) || repeatedSentence(candidate.linkedinPost)) reasons.push("repeated_sentences");
  if (containsMetaLanguage(all) || containsMetaLanguage(candidate.linkedinPost)) reasons.push("ai_meta_language");

  if (jaccard(`${candidate.headline} ${candidate.body} ${candidate.closing}`, candidate.linkedinPost) >= 0.58) {
    reasons.push("card_too_similar_to_linkedin");
  }
  if (jaccard(candidate.body, candidate.closing) >= 0.68) reasons.push("closing_repeats_body");
  if (jaccard(candidate.headline, candidate.body) >= 0.75) reasons.push("headline_repeats_body");

  return { pass: reasons.length === 0, score: reasons.length ? Math.max(0, 10 - reasons.length * 1.5) : 10, reasons };
}

export async function judgePostcardQuality(candidate: PostcardCandidate): Promise<QualityResult> {
  const deterministic = evaluatePostcardDeterministic(candidate);
  if (!deterministic.pass) return deterministic;

  const provider = await getAIProvider();
  const prompt = `You are PostCraft's final content quality editor.

Judge the candidate for a social post and visual card. We want feel-good, warm, thoughtful stories that are easy to understand and sound human. Facts do not need to be verified; fictional or loosely inspired stories are allowed. Do not penalize creativity or factual uncertainty.

Score these five qualities from 0 to 10:
- human: sounds like a real person, not corporate or AI-written
- simple: easy to understand on the first read
- emotional: leaves the reader feeling hopeful, inspired, or thoughtfully uplifted
- story: has a clear hook, movement/turning point, and memorable takeaway when appropriate
- distinct: the short card complements the longer LinkedIn post instead of repeating it

Candidate:
HEADLINE: ${candidate.headline}
CARD BODY: ${candidate.body}
CARD CLOSING: ${candidate.closing}
LINKEDIN POST: ${candidate.linkedinPost}

Return only JSON: {"human":0,"simple":0,"emotional":0,"story":0,"distinct":0,"score":0,"reason":"short reason"}
Overall score must be the average of the five qualities, rounded to one decimal. PASS requires overall score >= 8 and no quality below 7.`;

  try {
    const raw = await provider.generateText(prompt, { temperature: 0, numPredict: 220 });
    const parsed = parseJsonObject(raw, "PostCard quality judge");
    const scores = ["human", "simple", "emotional", "story", "distinct"].map((key) => Number(parsed[key]));
    const valid = scores.every((score) => Number.isFinite(score) && score >= 0 && score <= 10);
    if (!valid) return { pass: false, score: 0, reasons: ["quality_judge_invalid"] };
    const score = Math.round((scores.reduce((sum, value) => sum + value, 0) / scores.length) * 10) / 10;
    const reasons = scores.some((value) => value < 7) ? ["quality_judge_below_threshold"] : [];
    if (score < 8) reasons.push("quality_score_below_threshold");
    return { pass: reasons.length === 0, score, reasons };
  } catch {
    return deterministic;
  }
}
